apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rivky-rizel-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: me-west1-docker.pkg.dev/devconnect-project/rivky-rizel-artifacts/dev_connect:latest
        ports:
        - containerPort: 8000
     tolerations:
      - key: "webapp"
        operator: "Equal"
        value: "mywebapp"
        effect: "NoExecute"
